### ISSUE TITLE
Max retries exceeded Error

### ISSUE THREAD

**Issue by ishandutta2007** [vasilysinitsin/Faces#13]
I just installed via pip and saved your sample code(With file example) to a file, placed an image in proper path and ran. This is what I see

> Traceback (most recent call last):
>   File "face.py", line 4, in <module>
>     image = faces.FaceAppImage(file=sad)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/faces/__init__.py", line 71, in __init__
>     post = requests.post(BASE_API_URL, headers=headers, files={'file': file})
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/requests/api.py", line 116, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/requests/api.py", line 60, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='ph-x-p.faceapp.io', port=443): Max retries exceeded with url: /api/v2.11/photos (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
>

**Comment by essa2307** [comment]
Same error

**Comment by manchiraju** [comment]
any solution for this issue?

**Comment by essa2307** [comment]
Unfortunately no.
